### ISSUE TITLE
use of yarn 4 via corepack

### ISSUE THREAD

**Issue by NiewView** [xddq/nodejs-typescript-modern-starter#57]
Hi xddq,

thanks for providing this starter template.
One thing to note. You should no longer install yarn globally with `npm install -g yarn`, but use corepack:
https://yarnpkg.com/getting-started/install

Additionally Yarn 4 came out ;-)

PS: if it is wished I can make a PR for it.

**Comment by xddq** [comment]
Hey @NiewView,

you are welcome! It feels weird that yarn suggests using an experimental feature as the best practice. However, since they seemed to "join forces with the nodejs team to develop corepack" [src](https://yarnpkg.com/corepack) I assume they know what they are doing.

> PS: if it is wished I can make a PR for it.
Sure thing! Feel free to create a PR : ) I would say we upgrade to yarn 4 and use corepack in the same PR.
